import { GameConfigSchema } from "../dsl/schema";
import type { GameConfig } from "../dsl/schema";

/** Simple platformer: ground, platforms, collectibles, score win. */
export const EXAMPLE_PLATFORMER_CONFIG: GameConfig = GameConfigSchema.parse({
  meta: {
    title: "Jump Quest",
    description: "A simple platformer",
    genre: "platformer",
    viewport: { width: 800, height: 600 },
    backgroundColor: "#1a1a2e",
    gravity: { x: 0, y: 800 },
    cameraFollow: true,
    worldBounds: { width: 2400, height: 600 },
  },
  controls: {
    up: "ArrowUp",
    down: "ArrowDown",
    left: "ArrowLeft",
    right: "ArrowRight",
    action1: "Space",
    action2: "KeyZ",
    pause: "Escape",
  },
  player: {
    name: "Player",
    x: 100,
    y: 400,
    width: 32,
    height: 48,
    speed: 200,
    jumpForce: -420,
    maxJumps: 1,
    health: 3,
    maxHealth: 3,
    lives: 3,
    invincibilityDuration: 1000,
    appearance: { type: "rectangle", color: "#4488ff" },
    abilities: [{ type: "jump", trigger: "action1" }],
    animations: {},
  },
  enemies: [
    {
      name: "Goomba",
      x: 400,
      y: 368,
      width: 32,
      height: 32,
      health: 1,
      damage: 1,
      speed: 60,
      scoreValue: 100,
      appearance: { type: "rectangle", color: "#cc4444" },
      behavior: {
        type: "patrol",
        patrolDistance: 150,
        patrolAxis: "horizontal",
      },
      animations: {},
      drops: [],
    },
  ],
  collectibles: [
    {
      name: "Coin",
      x: 250,
      y: 350,
      width: 20,
      height: 20,
      appearance: { type: "circle", color: "#ffdd00" },
      effect: "score",
      value: 10,
      respawn: false,
      animations: {},
    },
  ],
  platforms: [
    {
      x: 0,
      y: 536,
      width: 2400,
      height: 64,
      appearance: { type: "rectangle", color: "#555555" },
      type: "static",
    },
    {
      x: 200,
      y: 420,
      width: 160,
      height: 24,
      appearance: { type: "rectangle", color: "#6b4423" },
      type: "static",
    },
    {
      x: 500,
      y: 350,
      width: 120,
      height: 24,
      appearance: { type: "rectangle", color: "#6b4423" },
      type: "static",
    },
    {
      x: 750,
      y: 280,
      width: 100,
      height: 24,
      appearance: { type: "rectangle", color: "#6b4423" },
      type: "static",
    },
  ],
  projectileTypes: [],
  spawners: [],
  decorations: [],
  ui: {
    showHealthBar: true,
    showScore: true,
    showLives: true,
    showTimer: false,
    customText: [],
  },
  scenes: {
    menu: {
      title: "Jump Quest",
      subtitle: "Press Start",
      backgroundColor: "#1a1a2e",
      buttons: [{ label: "Start Game", action: "start" }],
    },
    gameOver: {
      winTitle: "You Win!",
      loseTitle: "Game Over",
      showScore: true,
      showRetryButton: true,
    },
  },
  rules: {
    winCondition: { type: "score", value: 50 },
    loseCondition: { type: "health-zero" },
    scoring: [
      { event: "collect", points: 10 },
      { event: "kill", points: 100 },
    ],
  },
  audio: {
    backgroundMusic: "none",
    sfx: {
      jump: true,
      collect: true,
      damage: true,
      shoot: false,
      enemyDeath: true,
      gameOver: true,
      win: true,
    },
  },
});

/** Top-down shooter with projectiles. */
export const EXAMPLE_TOPDOWN_CONFIG: GameConfig = GameConfigSchema.parse({
  meta: {
    title: "Space Shooter",
    description: "Top-down shooter",
    genre: "top-down",
    viewport: { width: 800, height: 600 },
    backgroundColor: "#0a0a1a",
    gravity: { x: 0, y: 0 },
    cameraFollow: true,
    worldBounds: { width: 1600, height: 1200 },
  },
  controls: {
    up: "ArrowUp",
    down: "ArrowDown",
    left: "ArrowLeft",
    right: "ArrowRight",
    action1: "Space",
    action2: "KeyZ",
    pause: "Escape",
  },
  player: {
    name: "Ship",
    x: 400,
    y: 500,
    width: 40,
    height: 40,
    speed: 220,
    jumpForce: 0,
    maxJumps: 1,
    health: 5,
    maxHealth: 5,
    lives: 3,
    invincibilityDuration: 1500,
    appearance: { type: "triangle", color: "#44aaff" },
    abilities: [
      {
        type: "shoot",
        trigger: "action1",
        projectileType: "bullet",
        cooldownMs: 200,
      },
    ],
    animations: {},
  },
  enemies: [
    {
      name: "Alien",
      x: 400,
      y: 200,
      width: 28,
      height: 28,
      health: 2,
      damage: 1,
      speed: 80,
      scoreValue: 150,
      appearance: { type: "circle", color: "#ff6644" },
      behavior: { type: "chase", chaseRange: 400, chaseSpeed: 100 },
      animations: {},
      drops: [],
    },
  ],
  collectibles: [],
  platforms: [],
  projectileTypes: [
    {
      name: "bullet",
      width: 8,
      height: 8,
      speed: 500,
      damage: 1,
      lifetime: 2000,
      appearance: { type: "circle", color: "#ffff00" },
      piercing: false,
      gravity: false,
    },
  ],
  spawners: [],
  decorations: [],
  ui: {
    showHealthBar: true,
    showScore: true,
    showLives: true,
    showTimer: false,
    customText: [],
  },
  scenes: {
    menu: {
      title: "Space Shooter",
      subtitle: "Press Start",
      backgroundColor: "#0a0a1a",
      buttons: [{ label: "Start Game", action: "start" }],
    },
    gameOver: {
      winTitle: "Victory!",
      loseTitle: "Game Over",
      showScore: true,
      showRetryButton: true,
    },
  },
  rules: {
    winCondition: { type: "score", value: 500 },
    loseCondition: { type: "health-zero" },
    scoring: [{ event: "kill", points: 150 }],
  },
  audio: {
    backgroundMusic: "none",
    sfx: {
      jump: false,
      collect: true,
      damage: true,
      shoot: true,
      enemyDeath: true,
      gameOver: true,
      win: true,
    },
  },
});

/** Endless runner: auto-move right, jump only, survive time. */
export const EXAMPLE_RUNNER_CONFIG: GameConfig = GameConfigSchema.parse({
  meta: {
    title: "Endless Runner",
    description: "Run and jump",
    genre: "endless-runner",
    viewport: { width: 800, height: 600 },
    backgroundColor: "#1a2a1a",
    gravity: { x: 0, y: 900 },
    cameraFollow: true,
    worldBounds: { width: 4000, height: 600 },
  },
  controls: {
    up: "ArrowUp",
    down: "ArrowDown",
    left: "ArrowLeft",
    right: "ArrowRight",
    action1: "Space",
    action2: "KeyZ",
    pause: "Escape",
  },
  player: {
    name: "Runner",
    x: 120,
    y: 400,
    width: 32,
    height: 48,
    speed: 280,
    jumpForce: -450,
    maxJumps: 1,
    health: 1,
    maxHealth: 1,
    lives: 1,
    invincibilityDuration: 0,
    appearance: { type: "rectangle", color: "#44cc88" },
    abilities: [{ type: "jump", trigger: "action1" }],
    animations: {},
  },
  enemies: [
    {
      name: "Obstacle",
      x: 0,
      y: 0,
      width: 40,
      height: 48,
      health: 1,
      damage: 1,
      speed: 0,
      scoreValue: 0,
      appearance: { type: "rectangle", color: "#884400" },
      behavior: { type: "stationary" },
      animations: {},
      drops: [],
    },
  ],
  collectibles: [],
  platforms: [
    {
      x: 0,
      y: 536,
      width: 4000,
      height: 64,
      appearance: { type: "rectangle", color: "#4a3728" },
      type: "static",
    },
  ],
  projectileTypes: [],
  spawners: [
    {
      enemyName: "Obstacle",
      x: 600,
      y: 400,
      spawnRadius: 30,
      interval: 2500,
      maxActive: 5,
      totalSpawns: 0,
      startDelay: 2000,
    },
  ],
  decorations: [],
  ui: {
    showHealthBar: false,
    showScore: true,
    showLives: false,
    showTimer: true,
    timerDirection: "up",
    timerSeconds: 60,
    customText: [],
  },
  scenes: {
    menu: {
      title: "Endless Runner",
      subtitle: "Press Start",
      backgroundColor: "#1a2a1a",
      buttons: [{ label: "Start Game", action: "start" }],
    },
    gameOver: {
      winTitle: "You Survived!",
      loseTitle: "Game Over",
      showScore: true,
      showRetryButton: true,
    },
  },
  rules: {
    winCondition: { type: "survive-time", value: 60 },
    loseCondition: { type: "health-zero" },
    scoring: [{ event: "survive-second", points: 10 }],
  },
  audio: {
    backgroundMusic: "none",
    sfx: {
      jump: true,
      collect: false,
      damage: true,
      shoot: false,
      enemyDeath: false,
      gameOver: true,
      win: true,
    },
  },
});

// ========== TURN-BASED EXAMPLES ==========

/** Tic-Tac-Toe: 3x3 grid, any-empty placement, 3-in-a-row. */
export const EXAMPLE_TICTACTOE_CONFIG: GameConfig = GameConfigSchema.parse({
  gameType: "turn-based",
  turnBased: {
    subGenre: "grid-game",
    common: {
      title: "Tic-Tac-Toe",
      description: "Classic 3-in-a-row",
      viewport: { width: 800, height: 600 },
      backgroundColor: "#1a1a2e",
      players: [
        { name: "Player 1", type: "human", color: "#4488ff", symbol: "X" },
        {
          name: "Player 2",
          type: "ai",
          aiDifficulty: "medium",
          color: "#ff4444",
          symbol: "O",
        },
      ],
      showTurnIndicator: true,
      winMessage: "{player} wins!",
      drawMessage: "It's a draw!",
      menu: { title: "Tic-Tac-Toe", subtitle: "", showPlayerSetup: true },
    },
    gridGame: {
      rows: 3,
      cols: 3,
      cellSize: 100,
      placement: "any-empty",
      winCondition: {
        type: "n-in-a-row",
        count: 3,
        directions: ["horizontal", "vertical", "diagonal-down", "diagonal-up"],
      },
      drawCondition: "board-full",
      pieceStyle: "symbol",
    },
  },
});

/** Hangman: classic word guessing. */
export const EXAMPLE_HANGMAN_CONFIG: GameConfig = GameConfigSchema.parse({
  gameType: "turn-based",
  turnBased: {
    subGenre: "word-game",
    common: {
      title: "Hangman",
      viewport: { width: 800, height: 600 },
      backgroundColor: "#1a1a2e",
      players: [
        { name: "Player 1", type: "human", color: "#4488ff", symbol: "" },
      ],
      menu: { title: "Hangman", showPlayerSetup: false },
    },
    wordGame: {
      subType: "hangman",
      wordSource: "built-in",
      wordCategory: "mixed",
      minWordLength: 4,
      maxWordLength: 8,
      hangman: { maxWrongGuesses: 6, showCategory: true, drawStyle: "classic" },
      letterDisplayStyle: "boxes",
      letterSize: 32,
    },
  },
});

/** Memory / Matching: 4x4 grid, shapes theme. */
export const EXAMPLE_MEMORY_CONFIG: GameConfig = GameConfigSchema.parse({
  gameType: "turn-based",
  turnBased: {
    subGenre: "memory-game",
    common: {
      title: "Memory Match",
      viewport: { width: 800, height: 600 },
      backgroundColor: "#1a1a2e",
      players: [
        { name: "Player 1", type: "human", color: "#4488ff", symbol: "" },
        {
          name: "Player 2",
          type: "ai",
          aiDifficulty: "easy",
          color: "#ff4444",
          symbol: "",
        },
      ],
      menu: { title: "Memory Match", showPlayerSetup: true },
    },
    memoryGame: {
      rows: 4,
      cols: 4,
      cardWidth: 80,
      cardHeight: 80,
      theme: "shapes",
      cardsFlippedPerTurn: 2,
      flipDuration: 400,
      mismatchShowTime: 1000,
      scoringMethod: "pairs-found",
      showMoveCounter: true,
    },
  },
});

/** Trivia: 10 questions. */
export const EXAMPLE_TRIVIA_CONFIG: GameConfig = GameConfigSchema.parse({
  gameType: "turn-based",
  turnBased: {
    subGenre: "trivia-game",
    common: {
      title: "Trivia Quiz",
      viewport: { width: 800, height: 600 },
      backgroundColor: "#1a1a2e",
      players: [
        { name: "Player 1", type: "human", color: "#4488ff", symbol: "" },
      ],
      menu: { title: "Trivia Quiz", showPlayerSetup: false },
    },
    triviaGame: {
      questionCount: 10,
      shuffleQuestions: true,
      shuffleAnswers: true,
      timeLimitPerQuestion: 15,
      showExplanation: true,
      pointsPerCorrect: 100,
      pointsPerWrong: 0,
      questions: [
        {
          question: "What is 2 + 2?",
          answers: ["3", "4", "5", "6"],
          correctIndex: 1,
          category: "Math",
          difficulty: "easy",
          points: 100,
        },
        {
          question: "Capital of France?",
          answers: ["London", "Berlin", "Paris", "Madrid"],
          correctIndex: 2,
          category: "Geography",
          difficulty: "easy",
          points: 100,
        },
        {
          question: "Largest planet?",
          answers: ["Earth", "Mars", "Jupiter", "Saturn"],
          correctIndex: 2,
          category: "Science",
          difficulty: "medium",
          points: 100,
        },
      ],
    },
  },
});

/** War: simple card game. */
export const EXAMPLE_WAR_CARD_CONFIG: GameConfig = GameConfigSchema.parse({
  gameType: "turn-based",
  turnBased: {
    subGenre: "card-game",
    common: {
      title: "War",
      viewport: { width: 800, height: 600 },
      backgroundColor: "#1a1a2e",
      players: [
        { name: "You", type: "human", color: "#4488ff", symbol: "" },
        {
          name: "Opponent",
          type: "ai",
          aiDifficulty: "medium",
          color: "#ff4444",
          symbol: "",
        },
      ],
      menu: { title: "War", showPlayerSetup: true },
    },
    cardGame: {
      subType: "war",
      useStandardDeck: true,
      standardDeckCount: 1,
      cardsPerPlayer: 26,
      winCondition: "most-cards",
    },
  },
});

/** Monopoly-lite: simplified 24-space property board. */
export const EXAMPLE_MONOPOLY_LITE_CONFIG: GameConfig = GameConfigSchema.parse({
  gameType: "turn-based",
  turnBased: {
    subGenre: "board-game",
    common: {
      title: "Monopoly Lite",
      viewport: { width: 800, height: 600 },
      backgroundColor: "#1a1a2e",
      players: [
        { name: "Player 1", type: "human", color: "#4488ff", symbol: "" },
        {
          name: "Player 2",
          type: "ai",
          aiDifficulty: "easy",
          color: "#ff4444",
          symbol: "",
        },
      ],
      menu: { title: "Monopoly Lite", showPlayerSetup: true },
    },
    boardGame: {
      subType: "property-trading",
      layout: "square-loop",
      spacesPerSide: 6,
      spaceWidth: 70,
      spaceHeight: 90,
      startingMoney: 1500,
      passGoAmount: 200,
      winCondition: "last-standing",
      spaces: [
        { id: 0, name: "Go", type: "start" },
        {
          id: 1,
          name: "Mediterranean",
          type: "property",
          propertyCost: 60,
          propertyRent: 2,
        },
        { id: 2, name: "Community", type: "community-chest" },
        {
          id: 3,
          name: "Baltic",
          type: "property",
          propertyCost: 80,
          propertyRent: 4,
        },
        { id: 4, name: "Tax", type: "tax", amount: 200 },
        { id: 5, name: "Railroad", type: "railroad", propertyCost: 200 },
        {
          id: 6,
          name: "Oriental",
          type: "property",
          propertyCost: 100,
          propertyRent: 6,
        },
        { id: 7, name: "Chance", type: "chance" },
        {
          id: 8,
          name: "Vermont",
          type: "property",
          propertyCost: 100,
          propertyRent: 6,
        },
        {
          id: 9,
          name: "Connecticut",
          type: "property",
          propertyCost: 120,
          propertyRent: 8,
        },
        { id: 10, name: "Jail", type: "jail" },
        {
          id: 11,
          name: "St. Charles",
          type: "property",
          propertyCost: 140,
          propertyRent: 10,
        },
        { id: 12, name: "Electric", type: "utility", propertyCost: 150 },
        {
          id: 13,
          name: "States",
          type: "property",
          propertyCost: 140,
          propertyRent: 10,
        },
        {
          id: 14,
          name: "Virginia",
          type: "property",
          propertyCost: 160,
          propertyRent: 12,
        },
        { id: 15, name: "Railroad", type: "railroad", propertyCost: 200 },
        {
          id: 16,
          name: "St. James",
          type: "property",
          propertyCost: 180,
          propertyRent: 14,
        },
        { id: 17, name: "Community", type: "community-chest" },
        {
          id: 18,
          name: "Tennessee",
          type: "property",
          propertyCost: 180,
          propertyRent: 14,
        },
        {
          id: 19,
          name: "New York",
          type: "property",
          propertyCost: 200,
          propertyRent: 16,
        },
        { id: 20, name: "Free Parking", type: "free-parking" },
        {
          id: 21,
          name: "Kentucky",
          type: "property",
          propertyCost: 220,
          propertyRent: 18,
        },
        { id: 22, name: "Chance", type: "chance" },
        {
          id: 23,
          name: "Illinois",
          type: "property",
          propertyCost: 240,
          propertyRent: 20,
        },
      ],
    },
  },
});
